name: CI/CD Pipeline to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-notes-app:latest .

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-notes-app:latest

  deploy:
    runs-on: [self-hosted]

    steps:
    - name: Pull and Run Docker Container on EC2
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-notes-app:latest
        docker stop notes-app || true
        docker rm notes-app || true
        docker run -d -p 80:80 --name notes-app -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} ${{ secrets.DOCKER_USERNAME }}/nodejs-notes-app:latest
